<a href="https://colab.research.google.com/github/GenoaroSJr/Cursos/blob/main/Segundo_Trabalho_de_IA_(UNIFEI).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Segundo trabalho de Inteligencia Artificial:
###Aprendizado de Máquina Supervisionado Classificatório

**Banco de dados:** vehicle 

**Ténicas:** BernoulliNB & BaggingClassifier

**Trabalho por:** Genoaro Soares Junior


## Importanto bibliotecas


In [73]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler

from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import BaggingClassifier

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import confusion_matrix

## Importando e tratando dados

In [74]:
#Baixando dados;
!wget "https://github.com/valerio-unifei/UNIFEI-IA-Aulas/raw/main/benchmark-datasets.zip" -O datasets.zip
!unzip datasets.zip
!rm datasets.zip

--2021-07-04 23:44:06--  https://github.com/valerio-unifei/UNIFEI-IA-Aulas/raw/main/benchmark-datasets.zip
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/valerio-unifei/UNIFEI-IA-Aulas/main/benchmark-datasets.zip [following]
--2021-07-04 23:44:07--  https://raw.githubusercontent.com/valerio-unifei/UNIFEI-IA-Aulas/main/benchmark-datasets.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1232196 (1.2M) [application/zip]
Saving to: ‘datasets.zip’

datasets.zip        100%[===================>]   1.17M  --.-KB/s    in 0.06s   

2021-07-04 23:44:07 (20.6 MB/s) - ‘datasets.zip’ saved [1232196/12321

In [75]:
#Selecionando tabela a ser utilizada;
data = pd.read_csv("/content/vehicle.csv")
data.head().min()

Compactness                    85
 Circularity                   41
 Distance_circularity          70
 Radius_ratio                 141
 Praxis_aspect_ratio           57
 Max_length_aspect_ratio        9
 Scatter_ratio                144
 Elongatedness                 32
 Praxis_rectangular            19
 Length_rectangular           143
 Major_variance               160
 Minor_variance               309
 Gyration_radius              127
 Major_skewness                63
 Minor_skewness                 6
 Minor_kurtosis                 9
 Major_kurtosis               180
 Hollows_ratio                183
 Class                       bus 
dtype: object

In [76]:
data.head().max()

Compactness                   104
 Circularity                   50
 Distance_circularity         106
 Radius_ratio                 209
 Praxis_aspect_ratio          103
 Max_length_aspect_ratio       52
 Scatter_ratio                207
 Elongatedness                 46
 Praxis_rectangular            23
 Length_rectangular           159
 Major_variance               241
 Minor_variance               635
 Gyration_radius              220
 Major_skewness               127
 Minor_skewness                14
 Minor_kurtosis                16
 Major_kurtosis               199
 Hollows_ratio                207
 Class                       van 
dtype: object

**Obs:** Avaliando a diferença de escla entre os valores, é possível observar que não há uma diferença significativa, portanto, não seria necessário fazer o Standardisation ou o Normalization. 

-- Tal procedimento será realizado após alguns passos pois a proposta exige.

In [77]:
#data.describe()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846 entries, 0 to 845
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Compactness               846 non-null    int64 
 1    Circularity              846 non-null    int64 
 2    Distance_circularity     846 non-null    int64 
 3    Radius_ratio             846 non-null    int64 
 4    Praxis_aspect_ratio      846 non-null    int64 
 5    Max_length_aspect_ratio  846 non-null    int64 
 6    Scatter_ratio            846 non-null    int64 
 7    Elongatedness            846 non-null    int64 
 8    Praxis_rectangular       846 non-null    int64 
 9    Length_rectangular       846 non-null    int64 
 10   Major_variance           846 non-null    int64 
 11   Minor_variance           846 non-null    int64 
 12   Gyration_radius          846 non-null    int64 
 13   Major_skewness           846 non-null    int64 
 14   Minor_skewness           

**Obs:** Não há dados faltantes no dataset, portanto, não é necessário fazer o tratamento desses dados. A classe do dataset é em valores categóricos, ou seja, são strings, para que o algoritmo possa fazer corretamente as contas necessárias, é preciso transformar esses valores em numéricos.

In [78]:
#Separando entre classe e previsores;
# x -> previsores; y -> classe
x = data.iloc[:,0:18].values
y = data.iloc[:,18].values

In [79]:
#Será utilizado o LabelEncoder para fazer a transformação dos atributos categóricos;
label_encoder = LabelEncoder()
y_encoder = label_encoder.fit_transform(y) 
# Os valores foram "numerizados", preservando os dados anteriores;
##print(y_encoder)

In [80]:
#Realizando o Standardisation
scaler = StandardScaler()
x_scaler = scaler.fit_transform(x)
#print(x) Não escalonado
#print(x_scaler) Escalonado

**Obs:** Os dados de "classe" (y_encoder), não será escalonado pois não há sentido na operação, uma vez que os valores não representam um range de "avaliação" ou "nota" mas sim uma classificação.

## Iniciando os modelos de aprendizado de máquina supervisionado classificador



> **Técnicas:** BernoulliNB & BaggingClassifier
>
> **Para os dados (já tratados):**
> 
> (x_scaler, y_encoder)
>
> **Extra - x não escalonado:**
>
> (x, y_encoder)



### Para os dados tratados

In [81]:
bernoulliUm = BernoulliNB()

cv_results = cross_validate(bernoulliUm, x_scaler, y_encoder, cv=10, scoring=['accuracy', 'recall_macro', 'precision_macro'])

accuracy_medio = sum(cv_results['test_accuracy'])/10
recall_medio = sum(cv_results['test_recall_macro'])/10
precision_medio = sum(cv_results['test_precision_macro'])/10

print("Accuracy_medio: ", accuracy_medio)
print("Recall_medio: ", recall_medio)
print("Precision_medio: ", precision_medio)

Accuracy_medio:  0.4597759103641456
Recall_medio:  0.46872294372294376
Precision_medio:  0.5153259445953478


In [82]:
# Matriz de confusão.
y_pred = bernoulliUm.fit(x_scaler,y_encoder)
y_pred = bernoulliUm.predict(x_scaler)

confusion_matrix(y_encoder, y_pred)

array([[ 46,  51,  19, 102],
       [ 10,  57,  76,  69],
       [  6,  45,  95,  71],
       [  0,   4,   6, 189]])

In [83]:
baggingUm = BaggingClassifier()

cv_results = cross_validate(baggingUm, x_scaler, y_encoder, cv=10, scoring=['accuracy', 'recall_macro', 'precision_macro'])

accuracy_medio = sum(cv_results['test_accuracy'])/10
recall_medio = sum(cv_results['test_recall_macro'])/10
precision_medio = sum(cv_results['test_precision_macro'])/10

print("Accuracy_medio: ", accuracy_medio)
print("Recall_medio: ", recall_medio)
print("Precision_medio: ", precision_medio)

Accuracy_medio:  0.7210364145658263
Recall_medio:  0.7243156185919344
Precision_medio:  0.7156272627095837


In [84]:
# Matriz de confusão.
y_pred = baggingUm.fit(x_scaler,y_encoder)
y_pred = baggingUm.predict(x_scaler)

confusion_matrix(y_encoder, y_pred)

array([[218,   0,   0,   0],
       [  2, 207,   3,   0],
       [  1,   8, 207,   1],
       [  0,   0,   0, 199]])

### Para x não escalonado

In [85]:
bernoulliDois = BernoulliNB()

cv_results = cross_validate(bernoulliDois, x, y_encoder, cv=10, scoring=['accuracy', 'recall_macro', 'precision_macro'])

accuracy_medio = sum(cv_results['test_accuracy'])/10
recall_medio = sum(cv_results['test_recall_macro'])/10
precision_medio = sum(cv_results['test_precision_macro'])/10

print("Accuracy_medio: ", accuracy_medio)
print("Recall_medio: ", recall_medio)
print("Precision_medio: ", precision_medio)

Accuracy_medio:  0.25894957983193273
Recall_medio:  0.25486557302346774
Precision_medio:  0.20829997936076222


In [86]:
# Matriz de confusão.
y_pred = bernoulliDois.fit(x_scaler,y_encoder)
y_pred = bernoulliDois.predict(x_scaler)

confusion_matrix(y_encoder, y_pred)

array([[ 46,  51,  19, 102],
       [ 10,  57,  76,  69],
       [  6,  45,  95,  71],
       [  0,   4,   6, 189]])

In [87]:
baggingDois = BaggingClassifier()

cv_results = cross_validate(baggingDois, x, y_encoder, cv=10, scoring=['accuracy', 'recall_macro', 'precision_macro'])

accuracy_medio = sum(cv_results['test_accuracy'])/10
recall_medio = sum(cv_results['test_recall_macro'])/10
precision_medio = sum(cv_results['test_precision_macro'])/10

print("Accuracy_medio: ", accuracy_medio)
print("Recall_medio: ", recall_medio)
print("Precision_medio: ", precision_medio)

Accuracy_medio:  0.7444957983193278
Recall_medio:  0.7475099681020734
Precision_medio:  0.7397084544412136


In [88]:
# Matriz de confusão.
y_pred = bernoulliDois.fit(x_scaler,y_encoder)
y_pred = bernoulliDois.predict(x_scaler)

confusion_matrix(y_encoder, y_pred)

array([[ 46,  51,  19, 102],
       [ 10,  57,  76,  69],
       [  6,  45,  95,  71],
       [  0,   4,   6, 189]])

**Obs:** Contrário do que se esperava no começo, o escalonamento dos dados deu uma diferença significativa para o método BernoulliNB, deixando o método, que não é bom para esse tipo de dado, ainda pior. No caso Bagging, a diferença entre não escalonado e escalonado não é significativa.